channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - einops
  - torchmetrics
  - wandb
  - pyyaml
  - scikit-learn
  - pandas
  - matplotlib
  - meshio
  - pytest
  - h5py
  - pip
  - pip:
      - kappabenchmark
      - kappaconfig
      - kappadata
      - kappamodules
      - kappaprofiler
      - kappautils
      - neuraloperator
      - torch_geometric
      - torch_harmonics # requirement for neuraloperator but not in dependency tree of neuraloperator
      - wget
      # for Transient Flow Dataset generation
      - fluidfoam
      - PyFoam
      - gmsh
      - meshio
      - shapely
      - scikit-learn